// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-4DlY5qPIXeVw6t8CawiE8c-wmWEIWQU',
    appId: '1:19136338809:web:24b0f8d54a3e7ed0e3eda8',
    messagingSenderId: '19136338809',
    projectId: 'chatappbac',
    authDomain: 'chatappbac.firebaseapp.com',
    storageBucket: 'chatappbac.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCi50bndaO9i9b0M6kkzLR-atNmjQBZaek',
    appId: '1:19136338809:android:4d4fec2556ecfcd3e3eda8',
    messagingSenderId: '19136338809',
    projectId: 'chatappbac',
    storageBucket: 'chatappbac.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOq7enNauN_urj5iKaPw07zrqaEUX8QxI',
    appId: '1:19136338809:ios:99aaa96cec72298fe3eda8',
    messagingSenderId: '19136338809',
    projectId: 'chatappbac',
    storageBucket: 'chatappbac.appspot.com',
    iosClientId: '19136338809-plgin5gg1po76mv93uhq62ac522thmdn.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatAppsBac',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOq7enNauN_urj5iKaPw07zrqaEUX8QxI',
    appId: '1:19136338809:ios:adf354249948a68de3eda8',
    messagingSenderId: '19136338809',
    projectId: 'chatappbac',
    storageBucket: 'chatappbac.appspot.com',
    iosClientId: '19136338809-uj0gdaf0h2ha21q2kj48c3t7f9u80r66.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatAppsBac.RunnerTests',
  );
}
